// Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// Date/time formatting symbols for a large subset of locales.
// DO NOT EDIT. This file is autogenerated from ICU data. See
// 'http://go/generate_datetime_pattern_dart.cc' (Google internal)
// File generated from CLDR ver. 46.0
library;

// MANUAL EDIT TO SUPPRESS WARNINGS IN GENERATED CODE
// ignore_for_file: unnecessary_const

/// Returns a Map from locale names to another Map that goes from skeletons
/// to the locale-specific formatting patterns.
/// Internal use only. Call initializeDateFormatting instead.
Map<String, Map<String, String>> dateTimePatternMap() => {
      /// Extended set of localized date/time patterns for locale en.
      'en': const {
        'd': 'd', // DAY
        'E': 'ccc', // ABBR_WEEKDAY
        'EEEE': 'cccc', // WEEKDAY
        'LLL': 'LLL', // ABBR_STANDALONE_MONTH
        'LLLL': 'LLLL', // STANDALONE_MONTH
        'M': 'L', // NUM_MONTH
        'Md': 'M/d', // NUM_MONTH_DAY
        'MEd': 'EEE, M/d', // NUM_MONTH_WEEKDAY_DAY
        'MMM': 'LLL', // ABBR_MONTH
        'MMMd': 'MMM d', // ABBR_MONTH_DAY
        'MMMEd': 'EEE, MMM d', // ABBR_MONTH_WEEKDAY_DAY
        'MMMM': 'LLLL', // MONTH
        'MMMMd': 'MMMM d', // MONTH_DAY
        'MMMMEEEEd': 'EEEE, MMMM d', // MONTH_WEEKDAY_DAY
        'QQQ': 'QQQ', // ABBR_QUARTER
        'QQQQ': 'QQQQ', // QUARTER
        'y': 'y', // YEAR
        'yM': 'M/y', // YEAR_NUM_MONTH
        'yMd': 'M/d/y', // YEAR_NUM_MONTH_DAY
        'yMEd': 'EEE, M/d/y', // YEAR_NUM_MONTH_WEEKDAY_DAY
        'yMMM': 'MMM y', // YEAR_ABBR_MONTH
        'yMMMd': 'MMM d, y', // YEAR_ABBR_MONTH_DAY
        'yMMMEd': 'EEE, MMM d, y', // YEAR_ABBR_MONTH_WEEKDAY_DAY
        'yMMMM': 'MMMM y', // YEAR_MONTH
        'yMMMMd': 'MMMM d, y', // YEAR_MONTH_DAY
        'yMMMMEEEEd': 'EEEE, MMMM d, y', // YEAR_MONTH_WEEKDAY_DAY
        'yQQQ': 'QQQ y', // YEAR_ABBR_QUARTER
        'yQQQQ': 'QQQQ y', // YEAR_QUARTER
        'H': 'HH', // HOUR24
        'Hm': 'HH:mm', // HOUR24_MINUTE
        'Hms': 'HH:mm:ss', // HOUR24_MINUTE_SECOND
        'j': 'h a', // HOUR
        'jm': 'h:mm a', // HOUR_MINUTE
        'jms': 'h:mm:ss a', // HOUR_MINUTE_SECOND
        'jmv': 'h:mm a v', // HOUR_MINUTE_GENERIC_TZ
        'jmz': 'h:mm a z', // HOUR_MINUTETZ
        'jz': 'h a z', // HOURGENERIC_TZ
        'm': 'm', // MINUTE
        'ms': 'mm:ss', // MINUTE_SECOND
        's': 's', // SECOND
        'v': 'v', // ABBR_GENERIC_TZ
        'z': 'z', // ABBR_SPECIFIC_TZ
        'zzzz': 'zzzz', // SPECIFIC_TZ
        'ZZZZ': 'ZZZZ' // ABBR_UTC_TZ
      },

      /// Extended set of localized date/time patterns for locale ru.
      'ru': const {
        'd': 'd', // DAY
        'E': 'ccc', // ABBR_WEEKDAY
        'EEEE': 'cccc', // WEEKDAY
        'LLL': 'LLL', // ABBR_STANDALONE_MONTH
        'LLLL': 'LLLL', // STANDALONE_MONTH
        'M': 'L', // NUM_MONTH
        'Md': 'dd.MM', // NUM_MONTH_DAY
        'MEd': 'EEE, dd.MM', // NUM_MONTH_WEEKDAY_DAY
        'MMM': 'LLL', // ABBR_MONTH
        'MMMd': 'd MMM', // ABBR_MONTH_DAY
        'MMMEd': 'ccc, d MMM', // ABBR_MONTH_WEEKDAY_DAY
        'MMMM': 'LLLL', // MONTH
        'MMMMd': 'd MMMM', // MONTH_DAY
        'MMMMEEEEd': 'cccc, d MMMM', // MONTH_WEEKDAY_DAY
        'QQQ': 'QQQ', // ABBR_QUARTER
        'QQQQ': 'QQQQ', // QUARTER
        'y': 'y', // YEAR
        'yM': 'MM.y', // YEAR_NUM_MONTH
        'yMd': 'dd.MM.y', // YEAR_NUM_MONTH_DAY
        'yMEd': 'ccc, dd.MM.y \'г\'.', // YEAR_NUM_MONTH_WEEKDAY_DAY
        'yMMM': 'LLL y \'г\'.', // YEAR_ABBR_MONTH
        'yMMMd': 'd MMM y \'г\'.', // YEAR_ABBR_MONTH_DAY
        'yMMMEd': 'EEE, d MMM y \'г\'.', // YEAR_ABBR_MONTH_WEEKDAY_DAY
        'yMMMM': 'LLLL y \'г\'.', // YEAR_MONTH
        'yMMMMd': 'd MMMM y \'г\'.', // YEAR_MONTH_DAY
        'yMMMMEEEEd': 'EEEE, d MMMM y \'г\'.', // YEAR_MONTH_WEEKDAY_DAY
        'yQQQ': 'QQQ y \'г\'.', // YEAR_ABBR_QUARTER
        'yQQQQ': 'QQQQ y \'г\'.', // YEAR_QUARTER
        'H': 'HH', // HOUR24
        'Hm': 'HH:mm', // HOUR24_MINUTE
        'Hms': 'HH:mm:ss', // HOUR24_MINUTE_SECOND
        'j': 'HH', // HOUR
        'jm': 'HH:mm', // HOUR_MINUTE
        'jms': 'HH:mm:ss', // HOUR_MINUTE_SECOND
        'jmv': 'HH:mm v', // HOUR_MINUTE_GENERIC_TZ
        'jmz': 'HH:mm z', // HOUR_MINUTETZ
        'jz': 'HH z', // HOURGENERIC_TZ
        'm': 'm', // MINUTE
        'ms': 'mm:ss', // MINUTE_SECOND
        's': 's', // SECOND
        'v': 'v', // ABBR_GENERIC_TZ
        'z': 'z', // ABBR_SPECIFIC_TZ
        'zzzz': 'zzzz', // SPECIFIC_TZ
        'ZZZZ': 'ZZZZ' // ABBR_UTC_TZ
      },

      /// Extended set of localized date/time patterns for locale tk.
      'tk': const {
        'd': 'd', // DAY
        'E': 'ccc', // ABBR_WEEKDAY
        'EEEE': 'cccc', // WEEKDAY
        'LLL': 'LLL', // ABBR_STANDALONE_MONTH
        'LLLL': 'LLLL', // STANDALONE_MONTH
        'M': 'L', // NUM_MONTH
        'Md': 'd/M', // NUM_MONTH_DAY
        'MEd': 'd/MM EEE', // NUM_MONTH_WEEKDAY_DAY
        'MMM': 'LLL', // ABBR_MONTH
        'MMMd': 'd MMM', // ABBR_MONTH_DAY
        'MMMEd': 'd MMM EEE', // ABBR_MONTH_WEEKDAY_DAY
        'MMMM': 'LLLL', // MONTH
        'MMMMd': 'd MMMM', // MONTH_DAY
        'MMMMEEEEd': 'd MMMM EEEE', // MONTH_WEEKDAY_DAY
        'QQQ': 'QQQ', // ABBR_QUARTER
        'QQQQ': 'QQQQ', // QUARTER
        'y': 'y', // YEAR
        'yM': 'MM/y', // YEAR_NUM_MONTH
        'yMd': 'dd.MM.y', // YEAR_NUM_MONTH_DAY
        'yMEd': 'd.M.y EEE', // YEAR_NUM_MONTH_WEEKDAY_DAY
        'yMMM': 'MMM y', // YEAR_ABBR_MONTH
        'yMMMd': 'd MMM y', // YEAR_ABBR_MONTH_DAY
        'yMMMEd': 'd MMM y EEE', // YEAR_ABBR_MONTH_WEEKDAY_DAY
        'yMMMM': 'MMMM y', // YEAR_MONTH
        'yMMMMd': 'd MMMM y', // YEAR_MONTH_DAY
        'yMMMMEEEEd': 'd MMMM y EEEE', // YEAR_MONTH_WEEKDAY_DAY
        'yQQQ': 'y QQQ', // YEAR_ABBR_QUARTER
        'yQQQQ': 'y QQQQ', // YEAR_QUARTER
        'H': 'HH', // HOUR24
        'Hm': 'HH:mm', // HOUR24_MINUTE
        'Hms': 'HH:mm:ss', // HOUR24_MINUTE_SECOND
        'j': 'HH', // HOUR
        'jm': 'HH:mm', // HOUR_MINUTE
        'jms': 'HH:mm:ss', // HOUR_MINUTE_SECOND
        'jmv': 'HH:mm v', // HOUR_MINUTE_GENERIC_TZ
        'jmz': 'HH:mm z', // HOUR_MINUTETZ
        'jz': 'HH z', // HOURGENERIC_TZ
        'm': 'm', // MINUTE
        'ms': 'mm:ss', // MINUTE_SECOND
        's': 's', // SECOND
        'v': 'v', // ABBR_GENERIC_TZ
        'z': 'z', // ABBR_SPECIFIC_TZ
        'zzzz': 'zzzz', // SPECIFIC_TZ
        'ZZZZ': 'ZZZZ' // ABBR_UTC_TZ
      },

      /// Extended set of localized date/time patterns for locale tr.
      'tr': const {
        'd': 'd', // DAY
        'E': 'ccc', // ABBR_WEEKDAY
        'EEEE': 'cccc', // WEEKDAY
        'LLL': 'LLL', // ABBR_STANDALONE_MONTH
        'LLLL': 'LLLL', // STANDALONE_MONTH
        'M': 'L', // NUM_MONTH
        'Md': 'd/M', // NUM_MONTH_DAY
        'MEd': 'd/MM EEE', // NUM_MONTH_WEEKDAY_DAY
        'MMM': 'LLL', // ABBR_MONTH
        'MMMd': 'd MMM', // ABBR_MONTH_DAY
        'MMMEd': 'd MMM EEE', // ABBR_MONTH_WEEKDAY_DAY
        'MMMM': 'LLLL', // MONTH
        'MMMMd': 'd MMMM', // MONTH_DAY
        'MMMMEEEEd': 'd MMMM EEEE', // MONTH_WEEKDAY_DAY
        'QQQ': 'QQQ', // ABBR_QUARTER
        'QQQQ': 'QQQQ', // QUARTER
        'y': 'y', // YEAR
        'yM': 'MM/y', // YEAR_NUM_MONTH
        'yMd': 'dd.MM.y', // YEAR_NUM_MONTH_DAY
        'yMEd': 'd.M.y EEE', // YEAR_NUM_MONTH_WEEKDAY_DAY
        'yMMM': 'MMM y', // YEAR_ABBR_MONTH
        'yMMMd': 'd MMM y', // YEAR_ABBR_MONTH_DAY
        'yMMMEd': 'd MMM y EEE', // YEAR_ABBR_MONTH_WEEKDAY_DAY
        'yMMMM': 'MMMM y', // YEAR_MONTH
        'yMMMMd': 'd MMMM y', // YEAR_MONTH_DAY
        'yMMMMEEEEd': 'd MMMM y EEEE', // YEAR_MONTH_WEEKDAY_DAY
        'yQQQ': 'y QQQ', // YEAR_ABBR_QUARTER
        'yQQQQ': 'y QQQQ', // YEAR_QUARTER
        'H': 'HH', // HOUR24
        'Hm': 'HH:mm', // HOUR24_MINUTE
        'Hms': 'HH:mm:ss', // HOUR24_MINUTE_SECOND
        'j': 'HH', // HOUR
        'jm': 'HH:mm', // HOUR_MINUTE
        'jms': 'HH:mm:ss', // HOUR_MINUTE_SECOND
        'jmv': 'HH:mm v', // HOUR_MINUTE_GENERIC_TZ
        'jmz': 'HH:mm z', // HOUR_MINUTETZ
        'jz': 'HH z', // HOURGENERIC_TZ
        'm': 'm', // MINUTE
        'ms': 'mm:ss', // MINUTE_SECOND
        's': 's', // SECOND
        'v': 'v', // ABBR_GENERIC_TZ
        'z': 'z', // ABBR_SPECIFIC_TZ
        'zzzz': 'zzzz', // SPECIFIC_TZ
        'ZZZZ': 'ZZZZ' // ABBR_UTC_TZ
      },
    };
