// Copyright (c) 2014, the Dart project authors.
// Please see the AUTHORS file
// for details. All rights reserved. Use of this source code
// is governed by a
// BSD-style license that can be found in the LICENSE file.

/// Date/time formatting symbols for all locales.
// DO NOT EDIT. This file is autogenerated by script.  See
// 'http://go/generate_datetime_constants.py' using the --for_dart
// flag.
// File generated from CLDR ver. 46
//
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library;

// MANUAL EDIT TO SUPPRESS WARNINGS IN GENERATED CODE
// ignore_for_file: unnecessary_new, prefer_single_quotes, directives_ordering

import "date_symbols.dart";
import "date_time_patterns.dart";
import "src/date_format_internal.dart";

/// This should be called for at least one [locale] before any date
/// formatting methods are called. It sets up the lookup for date
/// symbols. Both the [locale] and [ignored] parameter are ignored, as
/// the data for all locales is directly available.
Future<void> initializeDateFormatting([String? locale, String? ignored]) {
  initializeDateSymbols(dateTimeSymbolMap);
  initializeDatePatterns(dateTimePatternMap);
  return new Future.value();
}

/// Returns a Map from locale names to the DateSymbols instance for
/// that locale. Internal use only. Call initializeDateFormatting
/// instead.
Map<String, DateSymbols> dateTimeSymbolMap() => {
      // Date/time formatting symbols for locale en_ISO.
      "en_ISO": DateSymbols(
          NAME: 'en_ISO',
          ERAS: const ['BC', 'AD'],
          ERANAMES: const ['Before Christ', 'Anno Domini'],
          NARROWMONTHS: const [
            'J',
            'F',
            'M',
            'A',
            'M',
            'J',
            'J',
            'A',
            'S',
            'O',
            'N',
            'D'
          ],
          STANDALONENARROWMONTHS: const [
            'J',
            'F',
            'M',
            'A',
            'M',
            'J',
            'J',
            'A',
            'S',
            'O',
            'N',
            'D'
          ],
          MONTHS: const [
            'January',
            'February',
            'March',
            'April',
            'May',
            'June',
            'July',
            'August',
            'September',
            'October',
            'November',
            'December'
          ],
          STANDALONEMONTHS: const [
            'January',
            'February',
            'March',
            'April',
            'May',
            'June',
            'July',
            'August',
            'September',
            'October',
            'November',
            'December'
          ],
          SHORTMONTHS: const [
            'Jan',
            'Feb',
            'Mar',
            'Apr',
            'May',
            'Jun',
            'Jul',
            'Aug',
            'Sep',
            'Oct',
            'Nov',
            'Dec'
          ],
          STANDALONESHORTMONTHS: const [
            'Jan',
            'Feb',
            'Mar',
            'Apr',
            'May',
            'Jun',
            'Jul',
            'Aug',
            'Sep',
            'Oct',
            'Nov',
            'Dec'
          ],
          WEEKDAYS: const [
            'Sunday',
            'Monday',
            'Tuesday',
            'Wednesday',
            'Thursday',
            'Friday',
            'Saturday'
          ],
          STANDALONEWEEKDAYS: const [
            'Sunday',
            'Monday',
            'Tuesday',
            'Wednesday',
            'Thursday',
            'Friday',
            'Saturday'
          ],
          SHORTWEEKDAYS: const [
            'Sun',
            'Mon',
            'Tue',
            'Wed',
            'Thu',
            'Fri',
            'Sat'
          ],
          STANDALONESHORTWEEKDAYS: const [
            'Sun',
            'Mon',
            'Tue',
            'Wed',
            'Thu',
            'Fri',
            'Sat'
          ],
          NARROWWEEKDAYS: const ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
          STANDALONENARROWWEEKDAYS: const ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
          SHORTQUARTERS: const ['Q1', 'Q2', 'Q3', 'Q4'],
          QUARTERS: const [
            '1st quarter',
            '2nd quarter',
            '3rd quarter',
            '4th quarter'
          ],
          AMPMS: const ['AM', 'PM'],
          DATEFORMATS: const [
            'EEEE, y MMMM dd',
            'y MMMM d',
            'y MMM d',
            'yyyy-MM-dd'
          ],
          TIMEFORMATS: const ['HH:mm:ss v', 'HH:mm:ss z', 'HH:mm:ss', 'HH:mm'],
          DATETIMEFORMATS: const [
            '{1} \'at\' {0}',
            '{1} \'at\' {0}',
            '{1}, {0}',
            '{1}, {0}'
          ],
          FIRSTDAYOFWEEK: 0,
          WEEKENDRANGE: const [5, 6],
          FIRSTWEEKCUTOFFDAY: 3),

      // Date/time formatting symbols for locale en.
      "en": new DateSymbols(
          NAME: "en",
          ERAS: const ['BC', 'AD'],
          ERANAMES: const ['Before Christ', 'Anno Domini'],
          NARROWMONTHS: const [
            'J',
            'F',
            'M',
            'A',
            'M',
            'J',
            'J',
            'A',
            'S',
            'O',
            'N',
            'D'
          ],
          STANDALONENARROWMONTHS: const [
            'J',
            'F',
            'M',
            'A',
            'M',
            'J',
            'J',
            'A',
            'S',
            'O',
            'N',
            'D'
          ],
          MONTHS: const [
            'January',
            'February',
            'March',
            'April',
            'May',
            'June',
            'July',
            'August',
            'September',
            'October',
            'November',
            'December'
          ],
          STANDALONEMONTHS: const [
            'January',
            'February',
            'March',
            'April',
            'May',
            'June',
            'July',
            'August',
            'September',
            'October',
            'November',
            'December'
          ],
          SHORTMONTHS: const [
            'Jan',
            'Feb',
            'Mar',
            'Apr',
            'May',
            'Jun',
            'Jul',
            'Aug',
            'Sep',
            'Oct',
            'Nov',
            'Dec'
          ],
          STANDALONESHORTMONTHS: const [
            'Jan',
            'Feb',
            'Mar',
            'Apr',
            'May',
            'Jun',
            'Jul',
            'Aug',
            'Sep',
            'Oct',
            'Nov',
            'Dec'
          ],
          WEEKDAYS: const [
            'Sunday',
            'Monday',
            'Tuesday',
            'Wednesday',
            'Thursday',
            'Friday',
            'Saturday'
          ],
          STANDALONEWEEKDAYS: const [
            'Sunday',
            'Monday',
            'Tuesday',
            'Wednesday',
            'Thursday',
            'Friday',
            'Saturday'
          ],
          SHORTWEEKDAYS: const [
            'Sun',
            'Mon',
            'Tue',
            'Wed',
            'Thu',
            'Fri',
            'Sat'
          ],
          STANDALONESHORTWEEKDAYS: const [
            'Sun',
            'Mon',
            'Tue',
            'Wed',
            'Thu',
            'Fri',
            'Sat'
          ],
          NARROWWEEKDAYS: const ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
          STANDALONENARROWWEEKDAYS: const ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
          SHORTQUARTERS: const ['Q1', 'Q2', 'Q3', 'Q4'],
          QUARTERS: const [
            '1st quarter',
            '2nd quarter',
            '3rd quarter',
            '4th quarter'
          ],
          AMPMS: const ['AM', 'PM'],
          DATEFORMATS: const [
            'EEEE, MMMM d, y',
            'MMMM d, y',
            'MMM d, y',
            'M/d/yy'
          ],
          TIMEFORMATS: const [
            'h:mm:ss a zzzz',
            'h:mm:ss a z',
            'h:mm:ss a',
            'h:mm a'
          ],
          DATETIMEFORMATS: const [
            '{1}, {0}',
            '{1}, {0}',
            '{1}, {0}',
            '{1}, {0}'
          ],
          FIRSTDAYOFWEEK: 6,
          WEEKENDRANGE: const [5, 6],
          FIRSTWEEKCUTOFFDAY: 5),
      // Date/time formatting symbols for locale ru.
      "ru": new DateSymbols(
          NAME: "ru",
          ERAS: const ['до н. э.', 'н. э.'],
          ERANAMES: const ['до Рождества Христова', 'от Рождества Христова'],
          NARROWMONTHS: const [
            'Я',
            'Ф',
            'М',
            'А',
            'М',
            'И',
            'И',
            'А',
            'С',
            'О',
            'Н',
            'Д'
          ],
          STANDALONENARROWMONTHS: const [
            'Я',
            'Ф',
            'М',
            'А',
            'М',
            'И',
            'И',
            'А',
            'С',
            'О',
            'Н',
            'Д'
          ],
          MONTHS: const [
            'января',
            'февраля',
            'марта',
            'апреля',
            'мая',
            'июня',
            'июля',
            'августа',
            'сентября',
            'октября',
            'ноября',
            'декабря'
          ],
          STANDALONEMONTHS: const [
            'январь',
            'февраль',
            'март',
            'апрель',
            'май',
            'июнь',
            'июль',
            'август',
            'сентябрь',
            'октябрь',
            'ноябрь',
            'декабрь'
          ],
          SHORTMONTHS: const [
            'янв.',
            'февр.',
            'мар.',
            'апр.',
            'мая',
            'июн.',
            'июл.',
            'авг.',
            'сент.',
            'окт.',
            'нояб.',
            'дек.'
          ],
          STANDALONESHORTMONTHS: const [
            'янв.',
            'февр.',
            'март',
            'апр.',
            'май',
            'июнь',
            'июль',
            'авг.',
            'сент.',
            'окт.',
            'нояб.',
            'дек.'
          ],
          WEEKDAYS: const [
            'воскресенье',
            'понедельник',
            'вторник',
            'среда',
            'четверг',
            'пятница',
            'суббота'
          ],
          STANDALONEWEEKDAYS: const [
            'воскресенье',
            'понедельник',
            'вторник',
            'среда',
            'четверг',
            'пятница',
            'суббота'
          ],
          SHORTWEEKDAYS: const ['вс', 'пн', 'вт', 'ср', 'чт', 'пт', 'сб'],
          STANDALONESHORTWEEKDAYS: const [
            'вс',
            'пн',
            'вт',
            'ср',
            'чт',
            'пт',
            'сб'
          ],
          NARROWWEEKDAYS: const ['В', 'П', 'В', 'С', 'Ч', 'П', 'С'],
          STANDALONENARROWWEEKDAYS: const ['В', 'П', 'В', 'С', 'Ч', 'П', 'С'],
          SHORTQUARTERS: const ['1-й кв.', '2-й кв.', '3-й кв.', '4-й кв.'],
          QUARTERS: const [
            '1-й квартал',
            '2-й квартал',
            '3-й квартал',
            '4-й квартал'
          ],
          AMPMS: const ['AM', 'PM'],
          DATEFORMATS: const [
            'EEEE, d MMMM y \'г\'.',
            'd MMMM y \'г\'.',
            'd MMM y \'г\'.',
            'dd.MM.y'
          ],
          TIMEFORMATS: const [
            'HH:mm:ss zzzz',
            'HH:mm:ss z',
            'HH:mm:ss',
            'HH:mm'
          ],
          DATETIMEFORMATS: const [
            '{1}, {0}',
            '{1}, {0}',
            '{1}, {0}',
            '{1}, {0}'
          ],
          FIRSTDAYOFWEEK: 0,
          WEEKENDRANGE: const [5, 6],
          FIRSTWEEKCUTOFFDAY: 3),
      // Date/time formatting symbols for locale tk.
      "tk": new DateSymbols(
          NAME: "tk",
          ERAS: const ['BEÖ', 'BES'],
          ERANAMES: const ['Biziň Eýýamymyzdan Öň', 'Biziň Eýýamymyzdan Soň'],
          NARROWMONTHS: const [
            'Ý',
            'F',
            'M',
            'A',
            'M',
            'I',
            'I',
            'A',
            'S',
            'O',
            'N',
            'D'
          ],
          STANDALONENARROWMONTHS: const [
            'Ý',
            'F',
            'M',
            'A',
            'M',
            'I',
            'I',
            'A',
            'S',
            'O',
            'N',
            'D'
          ],
          MONTHS: const [
            'Ýanwar',
            'Fewral',
            'Mart',
            'Aprel',
            'Maýs',
            'Iýun',
            'Iýul',
            'Awgust',
            'Sentýabr',
            'Oktýabr',
            'Noýabr',
            'Dekabr'
          ],
          STANDALONEMONTHS: const [
            'Ýanwar',
            'Fewral',
            'Mart',
            'Aprel',
            'Maýs',
            'Iýun',
            'Iýul',
            'Awgust',
            'Sentýabr',
            'Oktýabr',
            'Noýabr',
            'Dekabr'
          ],
          SHORTMONTHS: const [
            'Ýan',
            'Few',
            'Mar',
            'Apr',
            'Maý',
            'Iýn',
            'Iýl',
            'Awg',
            'Sen',
            'Okt',
            'Noý',
            'Dek'
          ],
          STANDALONESHORTMONTHS: const [
            'Ýan',
            'Few',
            'Mar',
            'Apr',
            'Maý',
            'Iýn',
            'Iýl',
            'Awg',
            'Sen',
            'Okt',
            'Noý',
            'Dek'
          ],
          WEEKDAYS: const [
            'Ýekşenbe',
            'Duşenbe',
            'Sişenbe',
            'Çarşenbe',
            'Penşenbe',
            'Anna',
            'Şenbe'
          ],
          STANDALONEWEEKDAYS: const [
            'Ýekşenbe',
            'Duşenbe',
            'Sişenbe',
            'Çarşenbe',
            'Penşenbe',
            'Anna',
            'Şenbe'
          ],
          SHORTWEEKDAYS: const [
            'Ýek',
            'Duş',
            'Siş',
            'Çar',
            'Pen',
            'Ann',
            'Şen'
          ],
          STANDALONESHORTWEEKDAYS: const [
            'Ýek',
            'Duş',
            'Siş',
            'Çar',
            'Pen',
            'Ann',
            'Şen'
          ],
          NARROWWEEKDAYS: const ['Ý', 'D', 'S', 'Ç', 'P', 'A', 'Ş'],
          STANDALONENARROWWEEKDAYS: const ['Ý', 'D', 'S', 'Ç', 'P', 'A', 'Ş'],
          SHORTQUARTERS: const ['Ç1', 'Ç2', 'Ç3', 'Ç4'],
          QUARTERS: const ['1. çärýek', '2. çärýek', '3. çärýek', '4. çärýek'],
          AMPMS: const ['ÖÖ', 'ÖS'],
          DATEFORMATS: const ['d MMMM y EEEE', 'd MMMM y', 'd MMM y', 'd.MM.y'],
          TIMEFORMATS: const [
            'HH:mm:ss zzzz',
            'HH:mm:ss z',
            'HH:mm:ss',
            'HH:mm'
          ],
          DATETIMEFORMATS: const ['{1} {0}', '{1} {0}', '{1} {0}', '{1} {0}'],
          FIRSTDAYOFWEEK: 1,
          WEEKENDRANGE: const [6, 0],
          FIRSTWEEKCUTOFFDAY: 0),
      // Date/time formatting symbols for locale tr.
      "tr": new DateSymbols(
          NAME: "tr",
          ERAS: const ['MÖ', 'MS'],
          ERANAMES: const ['Milattan Önce', 'Milattan Sonra'],
          NARROWMONTHS: const [
            'O',
            'Ş',
            'M',
            'N',
            'M',
            'H',
            'T',
            'A',
            'E',
            'E',
            'K',
            'A'
          ],
          STANDALONENARROWMONTHS: const [
            'O',
            'Ş',
            'M',
            'N',
            'M',
            'H',
            'T',
            'A',
            'E',
            'E',
            'K',
            'A'
          ],
          MONTHS: const [
            'Ocak',
            'Şubat',
            'Mart',
            'Nisan',
            'Mayıs',
            'Haziran',
            'Temmuz',
            'Ağustos',
            'Eylül',
            'Ekim',
            'Kasım',
            'Aralık'
          ],
          STANDALONEMONTHS: const [
            'Ocak',
            'Şubat',
            'Mart',
            'Nisan',
            'Mayıs',
            'Haziran',
            'Temmuz',
            'Ağustos',
            'Eylül',
            'Ekim',
            'Kasım',
            'Aralık'
          ],
          SHORTMONTHS: const [
            'Oca',
            'Şub',
            'Mar',
            'Nis',
            'May',
            'Haz',
            'Tem',
            'Ağu',
            'Eyl',
            'Eki',
            'Kas',
            'Ara'
          ],
          STANDALONESHORTMONTHS: const [
            'Oca',
            'Şub',
            'Mar',
            'Nis',
            'May',
            'Haz',
            'Tem',
            'Ağu',
            'Eyl',
            'Eki',
            'Kas',
            'Ara'
          ],
          WEEKDAYS: const [
            'Pazar',
            'Pazartesi',
            'Salı',
            'Çarşamba',
            'Perşembe',
            'Cuma',
            'Cumartesi'
          ],
          STANDALONEWEEKDAYS: const [
            'Pazar',
            'Pazartesi',
            'Salı',
            'Çarşamba',
            'Perşembe',
            'Cuma',
            'Cumartesi'
          ],
          SHORTWEEKDAYS: const [
            'Paz',
            'Pzt',
            'Sal',
            'Çar',
            'Per',
            'Cum',
            'Cmt'
          ],
          STANDALONESHORTWEEKDAYS: const [
            'Paz',
            'Pzt',
            'Sal',
            'Çar',
            'Per',
            'Cum',
            'Cmt'
          ],
          NARROWWEEKDAYS: const ['P', 'P', 'S', 'Ç', 'P', 'C', 'C'],
          STANDALONENARROWWEEKDAYS: const ['P', 'P', 'S', 'Ç', 'P', 'C', 'C'],
          SHORTQUARTERS: const ['Ç1', 'Ç2', 'Ç3', 'Ç4'],
          QUARTERS: const ['1. çeyrek', '2. çeyrek', '3. çeyrek', '4. çeyrek'],
          AMPMS: const ['ÖÖ', 'ÖS'],
          DATEFORMATS: const ['d MMMM y EEEE', 'd MMMM y', 'd MMM y', 'd.MM.y'],
          TIMEFORMATS: const [
            'HH:mm:ss zzzz',
            'HH:mm:ss z',
            'HH:mm:ss',
            'HH:mm'
          ],
          DATETIMEFORMATS: const ['{1} {0}', '{1} {0}', '{1} {0}', '{1} {0}'],
          FIRSTDAYOFWEEK: 0,
          WEEKENDRANGE: const [5, 6],
          FIRSTWEEKCUTOFFDAY: 6),
    };
