// Copyright (c) 2014, the Dart project authors.
// Please see the AUTHORS file
// for details. All rights reserved. Use of this source
// code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// Date/time formatting symbols for all locales.
// DO NOT EDIT. This file is autogenerated by script.  See
// http://go/generate_number_constants.py using the --for_dart flag.
// File generated from CLDR ver. 46
//
// Before checkin, this file could have been manually edited. This is
// to incorporate changes before we could correct CLDR. All manual
// modification must be documented in this section, and should be
// removed after those changes land to CLDR.
library;

// MANUAL EDIT TO SUPPRESS WARNINGS IN GENERATED CODE
// ignore_for_file: unnecessary_new, prefer_single_quotes, prefer_const_constructors
import "number_symbols.dart";

/// Map from locale to [NumberSymbols] used for that locale.
Map<String, NumberSymbols> numberFormatSymbols = <String, NumberSymbols>{
  // Number formatting symbols for locale en.
  "en": new NumberSymbols(
      NAME: "en",
      DECIMAL_SEP: '.',
      GROUP_SEP: ',',
      PERCENT: '%',
      ZERO_DIGIT: '0',
      PLUS_SIGN: '+',
      MINUS_SIGN: '-',
      EXP_SYMBOL: 'E',
      PERMILL: '\u2030',
      INFINITY: '\u221E',
      NAN: 'NaN',
      DECIMAL_PATTERN: '#,##0.###',
      SCIENTIFIC_PATTERN: '#E0',
      PERCENT_PATTERN: '#,##0%',
      CURRENCY_PATTERN: '\u00A4#,##0.00',
      DEF_CURRENCY_CODE: 'USD'),
  // Number formatting symbols for locale ru.
  "ru": new NumberSymbols(
      NAME: "ru",
      DECIMAL_SEP: ',',
      GROUP_SEP: '\u00A0',
      PERCENT: '%',
      ZERO_DIGIT: '0',
      PLUS_SIGN: '+',
      MINUS_SIGN: '-',
      EXP_SYMBOL: 'E',
      PERMILL: '\u2030',
      INFINITY: '\u221E',
      NAN: '\u043D\u0435\u00A0\u0447\u0438\u0441\u043B\u043E',
      DECIMAL_PATTERN: '#,##0.###',
      SCIENTIFIC_PATTERN: '#E0',
      PERCENT_PATTERN: '#,##0\u00A0%',
      CURRENCY_PATTERN: '#,##0.00\u00A0\u00A4',
      DEF_CURRENCY_CODE: 'RUB'),
  // Number formatting symbols for locale tk.
  "tk": new NumberSymbols(
      NAME: "tk",
      DECIMAL_SEP: ',',
      GROUP_SEP: '.',
      PERCENT: '%',
      ZERO_DIGIT: '0',
      PLUS_SIGN: '+',
      MINUS_SIGN: '-',
      EXP_SYMBOL: 'E',
      PERMILL: '\u2030',
      INFINITY: '\u221E',
      NAN: 'NaN',
      DECIMAL_PATTERN: '#,##0.###',
      SCIENTIFIC_PATTERN: '#E0',
      PERCENT_PATTERN: '%#,##0',
      CURRENCY_PATTERN: '\u00A4#,##0.00',
      DEF_CURRENCY_CODE: 'TMT'),
  // Number formatting symbols for locale tr.
  "tr": new NumberSymbols(
      NAME: "tr",
      DECIMAL_SEP: ',',
      GROUP_SEP: '.',
      PERCENT: '%',
      ZERO_DIGIT: '0',
      PLUS_SIGN: '+',
      MINUS_SIGN: '-',
      EXP_SYMBOL: 'E',
      PERMILL: '\u2030',
      INFINITY: '\u221E',
      NAN: 'NaN',
      DECIMAL_PATTERN: '#,##0.###',
      SCIENTIFIC_PATTERN: '#E0',
      PERCENT_PATTERN: '%#,##0',
      CURRENCY_PATTERN: '\u00A4#,##0.00',
      DEF_CURRENCY_CODE: 'TRY'),
};

Map<String, CompactNumberSymbols> compactNumberSymbols = {
  // Compact number symbols for locale en.
  "en": new CompactNumberSymbols(COMPACT_DECIMAL_SHORT_PATTERN: const {
    3: {'other': '0K'},
    6: {'other': '0M'},
    9: {'other': '0B'},
    12: {'other': '0T'},
  }, COMPACT_DECIMAL_LONG_PATTERN: const {
    3: {'other': '0 thousand'},
    6: {'other': '0 million'},
    9: {'other': '0 billion'},
    12: {'other': '0 trillion'},
  }, COMPACT_DECIMAL_SHORT_CURRENCY_PATTERN: const {
    3: {'other': '\u00A40K'},
    6: {'other': '\u00A40M'},
    9: {'other': '\u00A40B'},
    12: {'other': '\u00A40T'},
  }),
  // Compact number symbols for locale ru.
  "ru": new CompactNumberSymbols(COMPACT_DECIMAL_SHORT_PATTERN: const {
    3: {'other': '0\u00A0\u0442\u044B\u0441.'},
    6: {'other': '0\u00A0\u043C\u043B\u043D'},
    9: {'other': '0\u00A0\u043C\u043B\u0440\u0434'},
    12: {'other': '0\u00A0\u0442\u0440\u043B\u043D'},
  }, COMPACT_DECIMAL_LONG_PATTERN: const {
    3: {
      'few': '0 \u0442\u044B\u0441\u044F\u0447\u0438',
      'many': '0 \u0442\u044B\u0441\u044F\u0447',
      'one': '0 \u0442\u044B\u0441\u044F\u0447\u0430',
      'other': '0 \u0442\u044B\u0441\u044F\u0447\u0438',
    },
    6: {
      'few': '0 \u043C\u0438\u043B\u043B\u0438\u043E\u043D\u0430',
      'many': '0 \u043C\u0438\u043B\u043B\u0438\u043E\u043D\u043E\u0432',
      'one': '0 \u043C\u0438\u043B\u043B\u0438\u043E\u043D',
      'other': '0 \u043C\u0438\u043B\u043B\u0438\u043E\u043D\u0430',
    },
    9: {
      'few': '0 \u043C\u0438\u043B\u043B\u0438\u0430\u0440\u0434\u0430',
      'many': '0 \u043C\u0438\u043B\u043B\u0438\u0430\u0440\u0434\u043E\u0432',
      'one': '0 \u043C\u0438\u043B\u043B\u0438\u0430\u0440\u0434',
      'other': '0 \u043C\u0438\u043B\u043B\u0438\u0430\u0440\u0434\u0430',
    },
    12: {
      'few': '0 \u0442\u0440\u0438\u043B\u043B\u0438\u043E\u043D\u0430',
      'many': '0 \u0442\u0440\u0438\u043B\u043B\u0438\u043E\u043D\u043E\u0432',
      'one': '0 \u0442\u0440\u0438\u043B\u043B\u0438\u043E\u043D',
      'other': '0 \u0442\u0440\u0438\u043B\u043B\u0438\u043E\u043D\u0430',
    },
  }, COMPACT_DECIMAL_SHORT_CURRENCY_PATTERN: const {
    3: {'other': '0\u00A0\u0442\u044B\u0441.\u00A0\u00A4'},
    6: {'other': '0\u00A0\u043C\u043B\u043D\u00A0\u00A4'},
    9: {'other': '0\u00A0\u043C\u043B\u0440\u0434\u00A0\u00A4'},
    12: {'other': '0\u00A0\u0442\u0440\u043B\u043D\u00A0\u00A4'},
  }),
  // Compact number symbols for locale si.
  "si": new CompactNumberSymbols(COMPACT_DECIMAL_SHORT_PATTERN: const {
    3: {'other': '\u0DAF0'},
    6: {'other': '\u0DB8\u0DD20'},
    9: {'other': '\u0DB6\u0DD20'},
    12: {'other': '\u0DA7\u0DCA\u200D\u0DBB\u0DD20'},
  }, COMPACT_DECIMAL_LONG_PATTERN: const {
    3: {'other': '\u0DAF\u0DC4\u0DC3 0'},
    6: {'other': '\u0DB8\u0DD2\u0DBD\u0DD2\u0DBA\u0DB1 0'},
    9: {'other': '\u0DB6\u0DD2\u0DBD\u0DD2\u0DBA\u0DB1 0'},
    12: {'other': '\u0DA7\u0DCA\u200D\u0DBB\u0DD2\u0DBD\u0DD2\u0DBA\u0DB1 0'},
  }, COMPACT_DECIMAL_SHORT_CURRENCY_PATTERN: const {
    3: {'other': '\u00A4\u0DAF0'},
    6: {'other': '\u00A4\u0DB8\u0DD20'},
    9: {'other': '\u00A4\u0DB6\u0DD20'},
    12: {'other': '\u00A4\u0DA7\u0DCA\u200D\u0DBB\u0DD20'},
  }),
  // Compact number symbols for locale tk.
  "tk": new CompactNumberSymbols(COMPACT_DECIMAL_SHORT_PATTERN: const {
    3: {'other': '0\u00A0M'},
    6: {'other': '0\u00A0Mn'},
    9: {'other': '0\u00A0Mr'},
    12: {'other': '0\u00A0Tn'},
  }, COMPACT_DECIMAL_LONG_PATTERN: const {
    3: {'other': '0 müň'},
    6: {'other': '0 milýon'},
    9: {'other': '0 milýar'},
    12: {'other': '0 trilýon'},
  }, COMPACT_DECIMAL_SHORT_CURRENCY_PATTERN: const {
    3: {'other': '0\u00A0M\u00A0\u00A4'},
    6: {'other': '0\u00A0Mn\u00A0\u00A4'},
    9: {'other': '0\u00A0Mr\u00A0\u00A4'},
    12: {'other': '0\u00A0Tn\u00A0\u00A4'},
  }),
  // Compact number symbols for locale tr.
  "tr": new CompactNumberSymbols(COMPACT_DECIMAL_SHORT_PATTERN: const {
    3: {'other': '0\u00A0B'},
    6: {'other': '0\u00A0Mn'},
    9: {'other': '0\u00A0Mr'},
    12: {'other': '0\u00A0Tn'},
  }, COMPACT_DECIMAL_LONG_PATTERN: const {
    3: {'other': '0 bin'},
    6: {'other': '0 milyon'},
    9: {'other': '0 milyar'},
    12: {'other': '0 trilyon'},
  }, COMPACT_DECIMAL_SHORT_CURRENCY_PATTERN: const {
    3: {'other': '0\u00A0B\u00A0\u00A4'},
    6: {'other': '0\u00A0Mn\u00A0\u00A4'},
    9: {'other': '0\u00A0Mr\u00A0\u00A4'},
    12: {'other': '0\u00A0Tn\u00A0\u00A4'},
  })
};

final currencyFractionDigits = {
  "ADP": 0,
  "AFN": 0,
  "ALL": 0,
  "AMD": 2,
  "BHD": 3,
  "BIF": 0,
  "BYN": 2,
  "BYR": 0,
  "CAD": 2,
  "CHF": 2,
  "CLF": 4,
  "CLP": 0,
  "COP": 2,
  "CRC": 2,
  "CZK": 2,
  "DEFAULT": 2,
  "DJF": 0,
  "DKK": 2,
  "ESP": 0,
  "GNF": 0,
  "GYD": 2,
  "HUF": 2,
  "IDR": 2,
  "IQD": 0,
  "IRR": 0,
  "ISK": 0,
  "ITL": 0,
  "JOD": 3,
  "JPY": 0,
  "KMF": 0,
  "KPW": 0,
  "KRW": 0,
  "KWD": 3,
  "LAK": 0,
  "LBP": 0,
  "LUF": 0,
  "LYD": 3,
  "MGA": 0,
  "MGF": 0,
  "MMK": 0,
  "MNT": 2,
  "MRO": 0,
  "MUR": 2,
  "NOK": 2,
  "OMR": 3,
  "PKR": 2,
  "PYG": 0,
  "RSD": 0,
  "RWF": 0,
  "SEK": 2,
  "SLE": 2,
  "SLL": 0,
  "SOS": 0,
  "STD": 0,
  "SYP": 0,
  "TMM": 0,
  "TND": 3,
  "TRL": 0,
  "TWD": 2,
  "TZS": 2,
  "UGX": 0,
  "UYI": 0,
  "UYW": 4,
  "UZS": 2,
  "VEF": 2,
  "VND": 0,
  "VUV": 0,
  "XAF": 0,
  "XOF": 0,
  "XPF": 0,
  "YER": 0,
  "ZMK": 0,
  "ZWD": 0,
};
