// Copyright (c) 2016, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/// Provides locale-specific plural rules.
// DO NOT EDIT. This file is autogenerated from ICU data. See
// 'generate_dart_pluralrules.dart' (Google internal)
//
// Each function does the calculation for one or more locales. These are done in terms of
// various values used by the CLDR syntax and defined by UTS #35
// http://unicode.org/reports/tr35/tr35-numbers.html#Plural_rules_syntax
//
// * n - absolute value of the source number (integer and decimals).
// * i	- integer digits of n.
// * v	- number of visible fraction digits in n, with trailing zeros.
// * w	- number of visible fraction digits in n, without trailing zeros.
// * f	- visible fractional digits in n, with trailing zeros.
// * t	- visible fractional digits in n, without trailing zeros.
library;

// Suppress naming issues as changing them might be breaking.
// ignore_for_file: constant_identifier_names, non_constant_identifier_names

import 'dart:math' as math;

typedef PluralRule = PluralCase Function();

/// The possible cases used in a plural rule.
enum PluralCase { ZERO, ONE, TWO, FEW, MANY, OTHER }

/// The default rule in case we don't have anything more specific for a locale.
PluralCase _default_rule() => OTHER;

/// This must be called before evaluating a new rule, because we're using
/// library-global state to both keep the rules terse and minimize space.
void startRuleEvaluation(num howMany, [int? precision = 0]) {
  _n = howMany;
  _precision = precision;
  _i = _n.round();
  _updateVF(_n);
  _updateWT(_v, _f);
}

/// The number whose [PluralCase] we are trying to find.
///
// This is library-global state, along with the other variables. This allows us
// to avoid calculating parameters that the functions don't need and also
// not introduce a subclass per locale or have instance tear-offs which
// we can't cache. This is fine as long as these methods aren't async, which
// they should never be.
num _n = 0;

/// The integer part of [_n]
int _i = 0;
int? _precision;

/// Returns the number of digits in the fractional part of a number
/// (3.1416 => 4)
///
/// Takes the item count [n] and uses [_precision].
/// That's because a just looking at the value of a number is not enough to
/// decide the plural form. For example "1 dollar" vs "1.00 dollars", the
/// value is 1, but how it is formatted also matters.
int _decimals(num n) {
  var str = _precision == null ? '$n' : n.toStringAsFixed(_precision!);
  var result = str.indexOf('.');
  return (result == -1) ? 0 : str.length - result - 1;
}

/// Calculates and sets the _v and _f as per CLDR plural rules.
///
/// The short names for parameters / return match the CLDR syntax and UTS #35
///     (https://unicode.org/reports/tr35/tr35-numbers.html#Plural_rules_syntax)
/// Takes the item count [n] and a [precision].
void _updateVF(num n) {
  var defaultDigits = 3;

  _v = _precision ?? math.min(_decimals(n), defaultDigits);

  var base = math.pow(10, _v) as int;
  _f = (n * base).floor() % base;
}

/// Calculates and sets _w and _t as per CLDR plural rules.
///
/// The short names for parameters / return match the CLDR syntax and UTS #35
///     (https://unicode.org/reports/tr35/tr35-numbers.html#Plural_rules_syntax)
/// @param v Calculated previously.
/// @param f Calculated previously.
void _updateWT(int v, int f) {
  if (f == 0) {
    // Unused, for now _w = 0;
    _t = 0;
    return;
  }

  while ((f % 10) == 0) {
    f = (f / 10).floor();
    v--;
  }

  // Unused, for now _w = v;
  _t = f;
}

/// Number of visible fraction digits.
int _v = 0;

/// Number of visible fraction digits without trailing zeros.
// Unused, for now int _w = 0;

/// The visible fraction digits in n, with trailing zeros.
int _f = 0;

/// The visible fraction digits in n, without trailing zeros.
int _t = 0;

// An example, for precision n = 3.1415 and precision = 7)
//   n  : 3.1415
// str n: 3.1415000 (the "formatted" n, 7 fractional digits)
//   i  : 3         (the integer part of n)
//   f  :   1415000 (the fractional part of n)
//   v  : 7         (how many digits in f)
//   t  :   1415    (f, without trailing 0s)
//   w  : 4         (how many digits in t)

PluralCase get ZERO => PluralCase.ZERO;
PluralCase get ONE => PluralCase.ONE;
PluralCase get TWO => PluralCase.TWO;
PluralCase get FEW => PluralCase.FEW;
PluralCase get MANY => PluralCase.MANY;
PluralCase get OTHER => PluralCase.OTHER;

PluralCase _ast_rule() {
  if ((_i == 1) && (_v == 0)) {
    return ONE;
  }
  return OTHER;
}

PluralCase _af_rule() {
  if (_n == 1) {
    return ONE;
  }
  return OTHER;
}

PluralCase _ru_rule() {
  if ((_v == 0) && (_i % 10 == 1) && !(_i % 100 == 11)) {
    return ONE;
  }
  if ((_v == 0) &&
      (_i % 10 == 2 || _i % 10 == 3 || _i % 10 == 4) &&
      !(_i % 100 == 12 || _i % 100 == 13 || _i % 100 == 14)) {
    return FEW;
  }
  if ((_v == 0) && (_i % 10 == 0) ||
      (_v == 0) &&
          (_i % 10 == 5 ||
              _i % 10 == 6 ||
              _i % 10 == 7 ||
              _i % 10 == 8 ||
              _i % 10 == 9) ||
      (_v == 0) &&
          (_i % 100 == 11 ||
              _i % 100 == 12 ||
              _i % 100 == 13 ||
              _i % 100 == 14)) {
    return MANY;
  }
  return OTHER;
}

final pluralRules = {
  'en_ISO': _ast_rule,
  'en': _ast_rule,
  'ru': _ru_rule,
  'tk': _af_rule,
  'tr': _af_rule,
  'default': _default_rule,
};

/// Do we have plural rules specific to [locale]
bool localeHasPluralRules(String locale) => pluralRules.containsKey(locale);
